# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import client_pb2 as protos_dot_client__pb2
from protos import worker_pb2 as protos_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/client_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FinishRequest = channel.unary_unary(
                '/pipescaler.Client/FinishRequest',
                request_serializer=protos_dot_client__pb2.InferenceResponse.SerializeToString,
                response_deserializer=protos_dot_client__pb2.InferenceResponseAck.FromString,
                _registered_method=True)
        self.SetRoutingTable = channel.unary_unary(
                '/pipescaler.Client/SetRoutingTable',
                request_serializer=protos_dot_worker__pb2.RoutingTableRequest.SerializeToString,
                response_deserializer=protos_dot_worker__pb2.RoutingTableResponse.FromString,
                _registered_method=True)


class ClientServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FinishRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRoutingTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FinishRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishRequest,
                    request_deserializer=protos_dot_client__pb2.InferenceResponse.FromString,
                    response_serializer=protos_dot_client__pb2.InferenceResponseAck.SerializeToString,
            ),
            'SetRoutingTable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRoutingTable,
                    request_deserializer=protos_dot_worker__pb2.RoutingTableRequest.FromString,
                    response_serializer=protos_dot_worker__pb2.RoutingTableResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipescaler.Client', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipescaler.Client', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Client(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FinishRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipescaler.Client/FinishRequest',
            protos_dot_client__pb2.InferenceResponse.SerializeToString,
            protos_dot_client__pb2.InferenceResponseAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRoutingTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipescaler.Client/SetRoutingTable',
            protos_dot_worker__pb2.RoutingTableRequest.SerializeToString,
            protos_dot_worker__pb2.RoutingTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
