# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/controller.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/controller.proto\x12\npipescaler\"B\n\x0eRegisterWorker\x12\x0e\n\x06hostID\x18\x01 \x01(\t\x12\x0e\n\x06hostIP\x18\x02 \x01(\t\x12\x10\n\x08hostPort\x18\x03 \x01(\t\"X\n\x16RegisterWorkerResponse\x12\x0c\n\x04lbIP\x18\x01 \x01(\t\x12\x0e\n\x06lbPort\x18\x02 \x01(\t\x12\x14\n\x07message\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message\"*\n\nRegisterLB\x12\x0c\n\x04lbIP\x18\x01 \x01(\t\x12\x0e\n\x06lbPort\x18\x02 \x01(\t\"%\n\x12RegisterLBResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa2\x01\n\nController\x12O\n\x0bWorkerSetup\x12\x1a.pipescaler.RegisterWorker\x1a\".pipescaler.RegisterWorkerResponse\"\x00\x12\x43\n\x07LBSetup\x12\x16.pipescaler.RegisterLB\x1a\x1e.pipescaler.RegisterLBResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERWORKER']._serialized_start=39
  _globals['_REGISTERWORKER']._serialized_end=105
  _globals['_REGISTERWORKERRESPONSE']._serialized_start=107
  _globals['_REGISTERWORKERRESPONSE']._serialized_end=195
  _globals['_REGISTERLB']._serialized_start=197
  _globals['_REGISTERLB']._serialized_end=239
  _globals['_REGISTERLBRESPONSE']._serialized_start=241
  _globals['_REGISTERLBRESPONSE']._serialized_end=278
  _globals['_CONTROLLER']._serialized_start=281
  _globals['_CONTROLLER']._serialized_end=443
# @@protoc_insertion_point(module_scope)
