# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/load_balancer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/load_balancer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/load_balancer.proto\x12\npipescaler\"\x1e\n\x0bLBHeartbeat\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x13LBHeartbeatResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x89\x01\n\x12RegisterWorkerAtLB\x12\x0e\n\x06hostID\x18\x01 \x01(\t\x12\x0e\n\x06hostIP\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\x12\r\n\x05\x61ppID\x18\x04 \x01(\t\x12\x0c\n\x04task\x18\x05 \x01(\t\x12\x13\n\x0bloadedModel\x18\x06 \x01(\t\x12\x13\n\x0binfer_level\x18\x07 \x01(\x05\"-\n\x1aRegisterWorkerAtLBResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"M\n\x0eRegisterClient\x12\x0e\n\x06hostID\x18\x01 \x01(\t\x12\x0e\n\x06hostIP\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\x12\r\n\x05\x61ppID\x18\x04 \x01(\t\")\n\x16RegisterClientResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xff\x01\n\x0cLoadBalancer\x12\x45\n\x07LBAlive\x12\x17.pipescaler.LBHeartbeat\x1a\x1f.pipescaler.LBHeartbeatResponse\"\x00\x12W\n\x0bWorkerSetup\x12\x1e.pipescaler.RegisterWorkerAtLB\x1a&.pipescaler.RegisterWorkerAtLBResponse\"\x00\x12O\n\x0b\x43lientSetup\x12\x1a.pipescaler.RegisterClient\x1a\".pipescaler.RegisterClientResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.load_balancer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LBHEARTBEAT']._serialized_start=42
  _globals['_LBHEARTBEAT']._serialized_end=72
  _globals['_LBHEARTBEATRESPONSE']._serialized_start=74
  _globals['_LBHEARTBEATRESPONSE']._serialized_end=112
  _globals['_REGISTERWORKERATLB']._serialized_start=115
  _globals['_REGISTERWORKERATLB']._serialized_end=252
  _globals['_REGISTERWORKERATLBRESPONSE']._serialized_start=254
  _globals['_REGISTERWORKERATLBRESPONSE']._serialized_end=299
  _globals['_REGISTERCLIENT']._serialized_start=301
  _globals['_REGISTERCLIENT']._serialized_end=378
  _globals['_REGISTERCLIENTRESPONSE']._serialized_start=380
  _globals['_REGISTERCLIENTRESPONSE']._serialized_end=421
  _globals['_LOADBALANCER']._serialized_start=424
  _globals['_LOADBALANCER']._serialized_end=679
# @@protoc_insertion_point(module_scope)
