# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import worker_pb2 as protos_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerDaemonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/pipescaler.WorkerDaemon/Heartbeat',
                request_serializer=protos_dot_worker__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=protos_dot_worker__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/pipescaler.WorkerDaemon/LoadModel',
                request_serializer=protos_dot_worker__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=protos_dot_worker__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.InitiateRequest = channel.unary_unary(
                '/pipescaler.WorkerDaemon/InitiateRequest',
                request_serializer=protos_dot_worker__pb2.InferenceRequest.SerializeToString,
                response_deserializer=protos_dot_worker__pb2.InferenceRequestAck.FromString,
                _registered_method=True)
        self.IntermediateRequest = channel.unary_unary(
                '/pipescaler.WorkerDaemon/IntermediateRequest',
                request_serializer=protos_dot_worker__pb2.InferenceRequest.SerializeToString,
                response_deserializer=protos_dot_worker__pb2.InferenceRequestAck.FromString,
                _registered_method=True)
        self.SetRoutingTable = channel.unary_unary(
                '/pipescaler.WorkerDaemon/SetRoutingTable',
                request_serializer=protos_dot_worker__pb2.RoutingTableRequest.SerializeToString,
                response_deserializer=protos_dot_worker__pb2.RoutingTableResponse.FromString,
                _registered_method=True)


class WorkerDaemonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitiateRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IntermediateRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRoutingTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=protos_dot_worker__pb2.HeartbeatRequest.FromString,
                    response_serializer=protos_dot_worker__pb2.HeartbeatResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=protos_dot_worker__pb2.LoadModelRequest.FromString,
                    response_serializer=protos_dot_worker__pb2.LoadModelResponse.SerializeToString,
            ),
            'InitiateRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateRequest,
                    request_deserializer=protos_dot_worker__pb2.InferenceRequest.FromString,
                    response_serializer=protos_dot_worker__pb2.InferenceRequestAck.SerializeToString,
            ),
            'IntermediateRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.IntermediateRequest,
                    request_deserializer=protos_dot_worker__pb2.InferenceRequest.FromString,
                    response_serializer=protos_dot_worker__pb2.InferenceRequestAck.SerializeToString,
            ),
            'SetRoutingTable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRoutingTable,
                    request_deserializer=protos_dot_worker__pb2.RoutingTableRequest.FromString,
                    response_serializer=protos_dot_worker__pb2.RoutingTableResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipescaler.WorkerDaemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipescaler.WorkerDaemon', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerDaemon(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipescaler.WorkerDaemon/Heartbeat',
            protos_dot_worker__pb2.HeartbeatRequest.SerializeToString,
            protos_dot_worker__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipescaler.WorkerDaemon/LoadModel',
            protos_dot_worker__pb2.LoadModelRequest.SerializeToString,
            protos_dot_worker__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitiateRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipescaler.WorkerDaemon/InitiateRequest',
            protos_dot_worker__pb2.InferenceRequest.SerializeToString,
            protos_dot_worker__pb2.InferenceRequestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IntermediateRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipescaler.WorkerDaemon/IntermediateRequest',
            protos_dot_worker__pb2.InferenceRequest.SerializeToString,
            protos_dot_worker__pb2.InferenceRequestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRoutingTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipescaler.WorkerDaemon/SetRoutingTable',
            protos_dot_worker__pb2.RoutingTableRequest.SerializeToString,
            protos_dot_worker__pb2.RoutingTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
